wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1683621389.930271
    t:
      1:
      - 55
      3:
      - 23
      4: 3.11.3
      5: 0.15.2
      8:
      - 2
      - 5
      - 13
